name: nbdev Test Notebooks
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Test with nbdev
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U nbdev
        echo "Doing editable install..."
        pip install -e ".[dev]"
        echo "Check we are starting with clean git checkout"
        if [[ `git status --porcelain -uno` ]]; then
          git diff
          echo "git status is not clean"
          false
        fi
        echo "Trying to strip out notebooks"
        nbdev_clean
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [[ `git status --porcelain -uno` ]]; then
          git status -uno
          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
          false
        fi
        nbdev_export
        if [[ `git status --porcelain -uno` ]]; then
          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
          git status -uno
          git diff
          exit 1;
        fi
        nbdev_test