name: Download Notebooks and Reply PR

# read-write repo token
# access to secrets
on: 
  workflow_run:
    workflows: ["Upload Modified Notebook List"]
    types:
      - completed
defaults:
  run: { shell: bash }
jobs:
  download_payload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        pip install -e .
        python .github/scripts/reply_pr.py